/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hejunsaturday_videoinpainting_VideoUntrunc */

#ifndef _Included_com_hejunsaturday_videoinpainting_VideoUntrunc
#define _Included_com_hejunsaturday_videoinpainting_VideoUntrunc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hejunsaturday_videoinpainting_VideoUntrunc
 * Method:    untruncVideoFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZZZZZIII)V
 */
JNIEXPORT void JNICALL Java_com_hejunsaturday_videoinpainting_VideoUntrunc_untruncVideoFile
  (JNIEnv *, jobject, jstring, jstring, jstring, jboolean, jboolean, jboolean, jboolean, jboolean, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
